server:
  port: 8081  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: auth-service
encrypt:
  key-store:
    alias: scab  #别名
    location: classpath:scba.jks  #KeyStore 证书库名称
    password: ${JKS_STORE_PWD:sc123321}   #证书库密码
    secret: ${JKS_KEY_PWD:sc123321}   #秘钥
sc:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.yjw.auth.controller
    title: 微服务基础 - 权限微服务接口文档
    description: 该服务用于管理权限相关信息
    contact-name: yjw·研究院
    contact-url: http://scab.yjw.cn/
    contact-email: scba@yjw.cn
    version: v1.0
  auth:
    resource:
      enable: true
      includeLoginPaths:
        - /menus/me
        - /accounts/logout
  jdbc:
    database: tj_auth
