<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.yjw</groupId>
        <artifactId>chat</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>moonshot-chat</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- Spring Web 用于构建 RESTful API -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Spring AI Moonshot 核心依赖，目前找不到这个依赖可以使用open AI 去调用 -->
<!--        <dependency>-->
<!--            <groupId>org.springframework.ai.moonshot</groupId>-->
<!--            <artifactId>moonshot-core</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.springaicommunity.moonshot</groupId>
            <artifactId>moonshot-core</artifactId>
            <version>0.1.0</version>
        </dependency>
        <!-- springboot starter -->
<!--        <dependency>-->
<!--            <groupId>org.springframework.ai</groupId>-->
<!--            <artifactId>spring-ai-moonshot-spring-boot-starter</artifactId>-->
<!--            <version>1.0.0-M6</version>-->
<!--        </dependency>-->

        <!-- Spring AI Chat Client -->
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-client-chat</artifactId>
            <version>1.0.0-M8</version>
        </dependency>
        <!-- Spring AI Model -->
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-model</artifactId>
            <version>1.0.0-M8</version>
        </dependency>
    </dependencies>

</project>