<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.yjw</groupId>
        <artifactId>mcp</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <version>${revision}</version>
    <artifactId>mcp-starter</artifactId>
    <packaging>pom</packaging>

    <description>Starter MCP</description>
    <name>Starter MCP</name>

    <modules>

       <module>server/mcp-stdio-server</module>
        <module>client/mcp-stdio-client</module>

        <module>server/mcp-webflux-server</module>
        <module>client/mcp-webflux-client</module>
        <module>server/mcp-streamable-webflux-server</module>
        <module>client/mcp-streamable-webflux-client</module>
        <module>server/mcp-annotation-server</module>
        <module>client/mcp-annotation-client</module>
        <module>server/mcp-streamable-webmvc-server</module>
        <module>client/mcp-streamble-client</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>${maven-deploy-plugin.version}</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
