# GraphRunController类的stream方法
POST http://localhost:18080/stream

###
# GraphRunController类的invoke方法
POST http://localhost:18080/invoke

## 你们的客服态度太差了，问题一直没有解决
## 这个产品用不了一个星期就坏了，质量太差了
## 这个产品的质量非常好，我很满意
