# MultiModelController类的image方法
GET http://localhost:7878/api/image

###
# MultiModelController类的streamImage方法
GET http://localhost:7878/api/stream/image

###
# MultiModelController类的video方法
GET http://localhost:7878/api/video
